spring.application.name=nikebackend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url =jdbc:mysql://localhost:3306/nikedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=nikhil
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
# REQUIRED to load data.sql with MySQL
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
